CREATE TABLE public.contact_submissions (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying NOT NULL,
    email character varying NOT NULL,
    phone character varying,
    subject character varying,
    message text NOT NULL,
    inquiry_type character varying DEFAULT 'general'::character varying CHECK (inquiry_type::text = ANY (ARRAY['general'::character varying, 'booking'::character varying, 'feedback'::character varying, 'complaint'::character varying, 'partnership'::character varying, 'other'::character varying]::text[])),
    status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'read'::character varying, 'replied'::character varying, 'resolved'::character varying, 'spam'::character varying]::text[])),
    replied_at timestamp with time zone,
    replied_by uuid,
    reply_message text,
    ip_address character varying,
    user_agent text,
    source_page character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT contact_submissions_pkey PRIMARY KEY (id),
    CONSTRAINT contact_submissions_replied_by_fkey FOREIGN KEY (replied_by) REFERENCES public.admin_users(id)
);
