-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE IF NOT EXISTS public.admin_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  name character varying NOT NULL,
  role character varying DEFAULT 'admin'::character varying CHECK (role::text = ANY (ARRAY['super_admin'::character varying, 'admin'::character varying, 'editor'::character varying]::text[])),
  avatar_url text,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.admin_activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  admin_id uuid,
  admin_email character varying,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  details jsonb,
  old_values jsonb,
  new_values jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_activity_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_users(id)
);

CREATE TABLE IF NOT EXISTS public.blog_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  color character varying DEFAULT '#2D5A47'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  excerpt text,
  content text,
  featured_image text,
  gallery text[] DEFAULT '{}',
  category_id uuid,
  tags text[] DEFAULT '{}',
  author_id uuid,
  author_name character varying,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'scheduled'::character varying, 'archived'::character varying]::text[])),
  published_at timestamp with time zone,
  scheduled_at timestamp with time zone,
  views integer DEFAULT 0,
  likes integer DEFAULT 0,
  meta_title character varying,
  meta_description text,
  is_featured boolean DEFAULT false,
  allow_comments boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.blog_categories(id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.admin_users(id)
);

CREATE TABLE IF NOT EXISTS public.villas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying UNIQUE,
  tagline character varying,
  description text,
  short_description character varying,
  price_per_night bigint NOT NULL DEFAULT 0,
  original_price bigint,
  cleaning_fee bigint DEFAULT 0,
  service_fee bigint DEFAULT 0,
  capacity integer NOT NULL DEFAULT 2,
  bedrooms integer NOT NULL DEFAULT 1,
  bathrooms integer NOT NULL DEFAULT 1,
  beds integer DEFAULT 1,
  location character varying DEFAULT 'Ubud, Bali'::character varying,
  address text,
  coordinates jsonb DEFAULT '{"lat": -8.5069, "lng": 115.2625}'::jsonb,
  main_image text,
  images text[] DEFAULT '{}',
  video_url text,
  virtual_tour_url text,
  amenities text[] DEFAULT '{}',
  highlights text[] DEFAULT '{}',
  house_rules text[] DEFAULT '{}',
  is_featured boolean DEFAULT false,
  is_available boolean DEFAULT true,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'maintenance'::character varying]::text[])),
  rating numeric DEFAULT 5.0 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  review_count integer DEFAULT 0,
  check_in_time character varying DEFAULT '14:00'::character varying,
  check_out_time character varying DEFAULT '11:00'::character varying,
  minimum_stay integer DEFAULT 1,
  max_nights integer DEFAULT 30,
  meta_title character varying,
  meta_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT villas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reference_number character varying NOT NULL UNIQUE,
  villa_id uuid,
  guest_name character varying NOT NULL,
  guest_email character varying NOT NULL,
  guest_phone character varying,
  guest_country character varying,
  guest_id_type character varying,
  guest_id_number character varying,
  check_in date NOT NULL,
  check_out date NOT NULL,
  guests integer NOT NULL DEFAULT 1,
  nights integer NOT NULL DEFAULT 1,
  base_price bigint,
  cleaning_fee bigint DEFAULT 0,
  service_fee bigint DEFAULT 0,
  discount_amount bigint DEFAULT 0,
  discount_code character varying,
  total_price bigint NOT NULL DEFAULT 0,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'checked_in'::character varying, 'checked_out'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'paid'::character varying, 'refunded'::character varying, 'failed'::character varying]::text[])),
  payment_method character varying,
  special_requests text,
  arrival_time character varying,
  notes text,
  cancelled_at timestamp with time zone,
  cancelled_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_villa_id_fkey FOREIGN KEY (villa_id) REFERENCES public.villas(id)
);

CREATE TABLE IF NOT EXISTS public.contact_submissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  subject character varying,
  message text NOT NULL,
  inquiry_type character varying DEFAULT 'general'::character varying CHECK (inquiry_type::text = ANY (ARRAY['general'::character varying, 'booking'::character varying, 'feedback'::character varying, 'complaint'::character varying, 'partnership'::character varying, 'other'::character varying]::text[])),
  status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'read'::character varying, 'replied'::character varying, 'resolved'::character varying, 'spam'::character varying]::text[])),
  replied_at timestamp with time zone,
  replied_by uuid,
  reply_message text,
  ip_address character varying,
  user_agent text,
  source_page character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT contact_submissions_replied_by_fkey FOREIGN KEY (replied_by) REFERENCES public.admin_users(id)
);

CREATE TABLE IF NOT EXISTS public.gallery_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying,
  description text,
  image_url text NOT NULL,
  thumbnail_url text,
  category character varying DEFAULT 'general'::character varying,
  villa_id uuid,
  tags text[] DEFAULT '{}',
  width integer,
  height integer,
  file_size integer,
  mime_type character varying,
  is_featured boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  photographer character varying,
  location character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.offers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  slug character varying UNIQUE,
  description text,
  short_description character varying,
  discount_type character varying NOT NULL CHECK (discount_type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying, 'nights_free'::character varying]::text[])),
  discount_value integer NOT NULL DEFAULT 0,
  promo_code character varying UNIQUE,
  banner_image text,
  badge_text character varying,
  badge_color character varying DEFAULT '#2D5A47'::character varying,
  start_date date,
  end_date date,
  minimum_nights integer DEFAULT 1,
  max_nights integer,
  min_booking_value bigint DEFAULT 0,
  applicable_villas text[] DEFAULT '{}',
  max_uses integer,
  current_uses integer DEFAULT 0,
  max_uses_per_guest integer DEFAULT 1,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  is_public boolean DEFAULT true,
  terms text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key character varying NOT NULL UNIQUE,
  value text,
  type character varying DEFAULT 'string'::character varying CHECK (type::text = ANY (ARRAY['string'::character varying, 'number'::character varying, 'boolean'::character varying, 'json'::character varying, 'html'::character varying]::text[])),
  category character varying DEFAULT 'general'::character varying,
  label character varying,
  description text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.testimonials (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  guest_name character varying NOT NULL,
  guest_country character varying,
  guest_avatar text,
  villa_id uuid,
  villa_name character varying,
  booking_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  review text,
  ratings jsonb DEFAULT '{}'::jsonb,
  source character varying DEFAULT 'direct'::character varying CHECK (source::text = ANY (ARRAY['direct'::character varying, 'google'::character varying, 'tripadvisor'::character varying, 'airbnb'::character varying, 'booking'::character varying]::text[])),
  source_url text,
  is_featured boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  host_response text,
  responded_at timestamp with time zone,
  responded_by uuid,
  review_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT testimonials_villa_id_fkey FOREIGN KEY (villa_id) REFERENCES public.villas(id),
  CONSTRAINT testimonials_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT testimonials_responded_by_fkey FOREIGN KEY (responded_by) REFERENCES public.admin_users(id)
);

CREATE TABLE IF NOT EXISTS public.villa_booked_dates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  villa_id uuid NOT NULL,
  booking_id uuid,
  booked_date date NOT NULL,
  status character varying DEFAULT 'booked'::character varying CHECK (status::text = ANY (ARRAY['booked'::character varying, 'blocked'::character varying, 'maintenance'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT villa_booked_dates_pkey PRIMARY KEY (id),
  CONSTRAINT villa_booked_dates_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT villa_booked_dates_villa_id_fkey FOREIGN KEY (villa_id) REFERENCES public.villas(id)
);
