CREATE TABLE public.page_views (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    path text,
    user_agent text,
    country text,
    city text,
    referrer text
);

-- Enable Row Level Security
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anonymous users to insert their own page view data.
-- This is safe because they can only insert and not read or update.
CREATE POLICY "Allow public insert" ON public.page_views
FOR INSERT WITH CHECK (true);

-- Note: There is no SELECT policy for client-side roles.
-- Data will be read via an Edge Function using the service_role key to bypass RLS.
